# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CropViewController'
  pod 'ZKProgressHUD', '5.0.1'
  pod 'PryntTrimmerView'
  pod 'mobile-ffmpeg-full-gpl', '~> 4.3.2'
  # Pods for demo
end
